import type { Component } from 'vue'
import {
  ApiOutlined,
  AppstoreOutlined,
  ApartmentOutlined,
  BookOutlined,
  CloudOutlined,
  ClusterOutlined,
  DatabaseOutlined,
  ExperimentOutlined,
  EyeOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  KeyOutlined,
  LineChartOutlined,
  MonitorOutlined,
  NodeIndexOutlined,
  PayCircleOutlined,
  DashboardOutlined,
  RobotOutlined,
  SafetyOutlined,
  SettingOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  PlayCircleOutlined,
  BranchesOutlined,
  SearchOutlined,
  CodeOutlined,
  CheckCircleOutlined,
} from '@ant-design/icons-vue'

const iconMap: Record<string, Component> = {
  dashboard: DashboardOutlined,
  robot: RobotOutlined,
  workflow: ApartmentOutlined,
  knowledge: BookOutlined,
  model: ExperimentOutlined,
  tool: ToolOutlined,
  prompt: FileTextOutlined,
  application: AppstoreOutlined,
  monitor: MonitorOutlined,
  log: FileSearchOutlined,
  trace: NodeIndexOutlined,
  observability: EyeOutlined,
  org: TeamOutlined,
  permission: SafetyOutlined,
  settings: SettingOutlined,
  billing: PayCircleOutlined,
  apps: AppstoreOutlined,
  agents: RobotOutlined,
  invocations: LineChartOutlined,
  tokens: ThunderboltOutlined,
  cost: PayCircleOutlined,
  'api-key': KeyOutlined,
  dataset: DatabaseOutlined,
  mcp: ApiOutlined,
  users: TeamOutlined,
  api: ApiOutlined,
  vector: DatabaseOutlined,
  queue: ClusterOutlined,
  storage: CloudOutlined,
  start: PlayCircleOutlined,
  branch: BranchesOutlined,
  search: SearchOutlined,
  llm: CodeOutlined,
  end: CheckCircleOutlined,
}

export function getMenuIcon(key: string): Component {
  return iconMap[key] || AppstoreOutlined
}
